# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test1',
                'doc_host': 'https://gbeane66.github.io',
                'git_url': 'https://github.com/gbeane66/test1',
                'lib_path': 'test1'},
  'syms': { 'test1.Exponential_decay': {'test1.Exponential_decay.exp_decay': ('new_nb1.html#exp_decay', 'test1/Exponential_decay.py')},
            'test1.core': {'test1.core.exp_decay': ('new_nb1.html#exp_decay', 'test1/core.py')}}}
