# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test1',
                'doc_host': 'https://gbeane66.github.io',
                'git_url': 'https://github.com/gbeane66/test1',
                'lib_path': 'test1'},
  'syms': {'test1.core': {'test1.core.foo': ('core.html#foo', 'test1/core.py')}}}
