# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/new_nb1.ipynb.

# %% auto 0
__all__ = ['summer']

# %% ../nbs/new_nb1.ipynb 3
def summer(a, # first value
           b, # second value
          ):
    return a + b # the sum of a and b
