# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['summer']

# %% ../nbs/00_core.ipynb 3
def summer(a, # first value
           b, # second value
          ):
    return a + b # the sum of a and b
